image: bradrydzewski/ruby:2.0.0
env:
  #- GOPATH=/var/cache/drone
script:
  - bundle
  - rake test
  - ruby simple.rb
services:
  #- redis
notify:
  email:
    recipients:
      #- brad@drone.io
      #- burke@drone.io
